# Generated by Django 4.0.4 on 2022-05-25 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=120, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email'),
        ),
    ]
