# Generated by Django 4.0.5 on 2022-06-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Automóveis'), (1, 'Ferramentas'), (2, 'Roupa'), (3, 'Imóveis'), (4, 'Eletrodomésticos'), (5, 'Desporto'), (6, 'Tecnologia'), (7, 'Lazer'), (8, 'Móveis'), (9, 'Outros')], null=True),
        ),
    ]
